# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0006_host_num_cpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e1a\u52a1\u540d\u79f0')),
                ('playbook', models.TextField(blank=True, null=True, verbose_name='\u90e8\u7f72\u811a\u672c')),
                ('host', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1',
                'verbose_name_plural': '\u4e1a\u52a1',
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7248\u672c\u540d\u79f0')),
                ('files', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u7248\u672c')),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='\u4e1a\u52a1\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u7248\u672c\u4fe1\u606f',
            },
        ),
    ]
