# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_host_num_cpus'),
        ('deploy_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='host',
        ),
        migrations.AddField(
            model_name='projecthost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='\u4e1a\u52a1'),
        ),
        migrations.AddField(
            model_name='project',
            name='host',
            field=models.ManyToManyField(blank=True, default='', null=True, through='deploy_manager.ProjectHost', to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
    ]
