# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0004_auto_20170120_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='project_version',
        ),
        migrations.AddField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='project',
            name='host',
            field=models.ManyToManyField(blank=True, default='', null=True, through='deploy_manager.ProjectHost', to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
        migrations.DeleteModel(
            name='ProjectFiles',
        ),
    ]
