# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_host_num_cpus'),
        ('deploy_manager', '0006_auto_20170120_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f5c\u4e1a\u540d\u79f0')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.ProjectVersion', verbose_name='\u7248\u672c')),
            ],
            options={
                'verbose_name': '\u90e8\u7f72\u4f5c\u4e1a',
                'verbose_name_plural': '\u90e8\u7f72\u4f5c\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='DeployJobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_message', models.TextField(blank=True, null=True, verbose_name='\u4f5c\u4e1a\u4fe1\u606f')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a\u540d')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.DeployJob', verbose_name='\u4f5c\u4e1a\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u90e8\u7f72\u8be6\u60c5',
                'verbose_name_plural': '\u90e8\u7f72\u8be6\u60c5',
            },
        ),
    ]
