# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0007_deployjob_deployjobdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthost',
            options={'verbose_name': '\u4e1a\u52a1\u4e3b\u673a', 'verbose_name_plural': '\u4e1a\u52a1\u4e3b\u673a'},
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='/home/kira/dev/github/saltops/doc/script/files', verbose_name='\u7248\u672c'),
        ),
    ]
