# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0009_auto_20170122_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e1a\u52a1\u6a21\u5757\u540d\u79f0')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='deploy_manager.ProjectModule')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1',
                'verbose_name_plural': '\u4e1a\u52a1',
            },
        ),
        migrations.AlterField(
            model_name='deployjob',
            name='deploy_status',
            field=models.IntegerField(blank=True, choices=[(0, '\u90e8\u7f72\u4e2d'), (1, '\u90e8\u7f72\u5b8c\u6210'), (2, '\u90e8\u7f72\u5931\u8d25')], default=0, null=True, verbose_name='\u90e8\u7f72\u72b6\u6001'),
        ),
    ]
