# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0010_auto_20170122_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodule',
            options={'verbose_name': '\u4e1a\u52a1\u6a21\u5757', 'verbose_name_plural': '\u4e1a\u52a1\u6a21\u5757'},
        ),
        migrations.AddField(
            model_name='project',
            name='project_module',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.ProjectModule', verbose_name='\u4e1a\u52a1\u6a21\u5757'),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='deploy_manager.ProjectModule', verbose_name='\u4e0a\u7ea7\u4e1a\u52a1\u6a21\u5757'),
        ),
    ]
