# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0012_projectversion_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployjobdetail',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u6267\u884c\u65f6\u957f'),
        ),
        migrations.AddField(
            model_name='deployjobdetail',
            name='job_cmd',
            field=models.TextField(blank=True, null=True, verbose_name='\u4f5c\u4e1a\u547d\u4ee4'),
        ),
        migrations.AddField(
            model_name='deployjobdetail',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='deployjobdetail',
            name='stderr',
            field=models.TextField(blank=True, null=True, verbose_name='\u5176\u4ed6\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='\u9ed8\u8ba4\u7248\u672c'),
        ),
    ]
