# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0014_deployjob_job_script_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployjob',
            name='job_script_type',
        ),
        migrations.AddField(
            model_name='projecthost',
            name='job_script_type',
            field=models.IntegerField(choices=[(0, 'salt sls'), (1, 'shell')], default=0, verbose_name='脚本语言'),
        ),
    ]
