# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0018_auto_20170128_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployjob',
            options={'verbose_name': '历史作业', 'verbose_name_plural': '历史作业'},
        ),
    ]
