# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0020_auto_20170129_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployjobdetail',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='提示信息'),
        ),
        migrations.AddField(
            model_name='deployjobdetail',
            name='run_num',
            field=models.IntegerField(default=0, verbose_name='执行顺序'),
        ),
    ]
