# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0021_auto_20170201_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployjobdetail',
            name='run_num',
        ),
    ]
