# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0022_remove_deployjobdetail_run_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployjobdetail',
            name='is_success',
            field=models.BooleanField(choices=[(True, '执行成功'), (False, '执行失败')], default=True, verbose_name='执行情况'),
        ),
    ]
