# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0023_deployjobdetail_is_success'),
        ('deploy_manager', '0013_auto_20170123_0737'),
    ]

    operations = [
    ]
