# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0024_merge_20170208_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='subplaybook',
            field=models.TextField(blank=True, help_text='为空则使用全局的部署脚本', null=True, verbose_name='部署脚本'),
        ),
    ]
