# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0028_auto_20170209_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_param',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展参数'),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='extra_param',
            field=models.TextField(blank=True, default='', null=True, verbose_name='扩展参数'),
        ),
    ]
