# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0030_auto_20170209_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='/home/kira/dev/saltops/doc/script/', verbose_name='版本'),
        ),
    ]
