# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0031_auto_20170212_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='/Users/kira/oschina/saltops/doc/script/', verbose_name='版本'),
        ),
    ]
