# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:58
from __future__ import unicode_literals

from django.db import migrations
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0032_auto_20170214_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='playbook',
            field=yamlfield.fields.YAMLField(blank=True, help_text='${version}代表默认版本号', null=True, verbose_name='部署脚本'),
        ),
    ]
