# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0033_auto_20170217_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_param',
            field=yamlfield.fields.YAMLField(blank=True, default='', null=True, verbose_name='扩展参数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='playbook',
            field=models.TextField(blank=True, help_text='${version}代表默认版本号', null=True, verbose_name='部署脚本'),
        ),
    ]
