# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0035_auto_20170217_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='anti_install_playbook',
            field=models.TextField(blank=True, help_text='${version}代表默认版本号', null=True, verbose_name='卸载脚本'),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='anti_install_playbook',
            field=models.TextField(blank=True, help_text='${version}代表默认版本号', null=True, verbose_name='卸载脚本'),
        ),
    ]
