# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0039_remove_project_project_config_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfigpath',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='业务名称'),
        ),
    ]
