# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0041_auto_20170219_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config_path', models.FilePathField(blank=True, null=True, verbose_name='配置文件路径')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='业务')),
            ],
            options={
                'verbose_name_plural': '业务配置',
                'verbose_name': '业务配置',
            },
        ),
    ]
