# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('eth1', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7f51\u53611')),
                ('eth2', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7f51\u53612')),
                ('mac', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC')),
                ('internal_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u8fdc\u63a7\u5361')),
                ('cpu', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU')),
                ('hard_disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u786c\u76d8')),
                ('memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5185\u5b58')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('guarantee_date', models.DateField(blank=True, null=True, verbose_name='\u4fdd\u4fee\u65f6\u95f4')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('editor', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('Services_Code', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5feb\u901f\u670d\u52a1\u7f16\u7801')),
                ('server_sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='SN\u7f16\u53f7')),
                ('switch_port', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea4\u6362\u673a\u7aef\u53e3\u53f7')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u865a\u62df\u673a\u7236\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a',
            },
        ),
    ]
