# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170119_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u4e3b\u673aIP',
                'verbose_name_plural': '\u4e3b\u673aIP',
            },
        ),
    ]
