# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_hostip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostip',
            name='host',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
    ]
