# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20170121_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Brand',
        ),
    ]
