# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20170121_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '\u8bbe\u5907\u578b\u53f7', 'verbose_name_plural': '\u8bbe\u5907\u578b\u53f7'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u578b\u53f7\u540d\u79f0'),
        ),
    ]
