# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20170121_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
