# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20170121_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u673a\u67dc\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u673a\u67dc',
                'verbose_name_plural': '\u673a\u67dc',
            },
        ),
    ]
