# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('bandwidth', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u673a\u623f\u5e26\u5bbd')),
                ('phone', models.CharField(max_length=255, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('linkman', models.CharField(max_length=255, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('network', models.TextField(blank=True, null=True, verbose_name='IP\u5730\u5740\u6bb5')),
                ('create_time', models.DateField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='IDCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u7c7b\u578b',
                'verbose_name_plural': '\u673a\u623f\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'ISP',
                'verbose_name_plural': 'ISP',
            },
        ),
        migrations.AddField(
            model_name='idc',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.ISP', verbose_name='ISP\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='idc',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDCType', verbose_name='\u673a\u623f\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='IDC'),
        ),
    ]
