# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20170122_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u673a\u67b6\u540d\u79f0')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='\u673a\u67dc')),
            ],
            options={
                'verbose_name': '\u673a\u67b6',
                'verbose_name_plural': '\u673a\u67b6',
            },
        ),
    ]
