# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Rack', verbose_name='\u673a\u67b6'),
        ),
    ]
