# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_host_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('comment', models.TextField(verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u7b49\u7ea7',
                'verbose_name_plural': '\u673a\u623f\u7b49\u7ea7',
            },
        ),
        migrations.AlterField(
            model_name='idc',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDCLevel', verbose_name='\u673a\u623f\u7c7b\u578b'),
        ),
        migrations.DeleteModel(
            name='IDCType',
        ),
    ]
