# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20170125_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isp',
            options={'verbose_name': 'ISP\u7c7b\u578b', 'verbose_name_plural': 'ISP\u7c7b\u578b'},
        ),
    ]
