# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20170125_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='concat_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1'),
        ),
    ]
