# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_idc_concat_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='机房'),
        ),
    ]
