# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_auto_20170128_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
