# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_auto_20170130_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='minion_status',
            field=models.IntegerField(choices=[(0, '未启动'), (1, '运行中')], default=0, verbose_name='Minion状态'),
        ),
    ]
