# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_host_minion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='enable_ssh',
            field=models.BooleanField(choices=[(True, '启用'), (False, '禁用')], default=False, verbose_name='使用Salt-SSH'),
        ),
        migrations.AddField(
            model_name='host',
            name='enable_sudo',
            field=models.BooleanField(choices=[(True, '启用'), (False, '禁用')], default=False, verbose_name='启用Sudo'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SSH密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_username',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SSH用户名'),
        ),
    ]
