# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0023_auto_20170209_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostip',
            name='ip_type',
            field=models.IntegerField(blank=True, choices=[(100, '----'), (0, '内网'), (1, '外网'), (2, '管理网')], default=100, verbose_name='IP类型'),
        ),
    ]
