# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0025_auto_20170211_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='idc',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='idc', chained_model_field='idc', on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='cabinet',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cabinet', chained_model_field='cabinet', on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='机柜'),
        ),
    ]
