# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0028_host_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='IDC'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cabinet',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='idc', chained_model_field='idc', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet'),
        ),
        migrations.AlterField(
            model_name='host',
            name='rack',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='cabinet', chained_model_field='cabinet', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Rack'),
        ),
    ]
