# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0029_auto_20170217_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='host',
            name='idc',
        ),
        migrations.AlterField(
            model_name='host',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Rack', verbose_name='机架'),
        ),
    ]
