# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0030_auto_20170217_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='rack',
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='IDC'),
        ),
    ]
