# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0034_auto_20170217_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='IDC'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='cabinet',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='idc', chained_model_field='idc', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='机柜'),
        ),
    ]
