# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toolsScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='工具名称')),
                ('tool_script', models.CharField(max_length=255, verbose_name='脚本')),
            ],
            options={
                'verbose_name_plural': '工具',
                'verbose_name': '工具',
            },
        ),
        migrations.CreateModel(
            name='toolsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类型名称')),
            ],
            options={
                'verbose_name_plural': '工具类型',
                'verbose_name': '工具类型',
            },
        ),
        migrations.AddField(
            model_name='toolsscript',
            name='tools_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_manager.toolsTypes', verbose_name='工具类型'),
        ),
    ]
