# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_manager', '0004_auto_20170128_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsscript',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='工具说明'),
        ),
        migrations.AlterField(
            model_name='toolsscript',
            name='tools_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_manager.ToolsTypes', verbose_name='工具类型'),
        ),
    ]
