# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_manager', '0029_auto_20170212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsscript',
            name='tool_run_type',
            field=models.IntegerField(choices=[(0, 'Salt脚本'), (1, 'Shell'), (2, 'PowerShell'), (3, 'Python')], default=0, verbose_name='脚本类型'),
        ),
        migrations.AlterField(
            model_name='toolsscript',
            name='tools_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_manager.ToolsTypes', verbose_name='工具类型'),
        ),
    ]
