# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0025_auto_20170211_2105'),
        ('tools_manager', '0031_auto_20170212_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsExecDetailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exec_result', models.TextField(blank=True, default='', null=True, verbose_name='执行结果')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='目标主机')),
            ],
            options={
                'verbose_name': '工具详细信息',
                'verbose_name_plural': '工具详细信息',
            },
        ),
        migrations.AlterModelOptions(
            name='toolsexechistory',
            options={'verbose_name': '任务详情', 'verbose_name_plural': '任务详情'},
        ),
        migrations.AlterField(
            model_name='toolsexechistory',
            name='tools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_manager.ToolsScript', verbose_name='工具'),
        ),
        migrations.AlterField(
            model_name='toolsscript',
            name='tools_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_manager.ToolsTypes', verbose_name='工具类型'),
        ),
        migrations.AddField(
            model_name='toolsexecdetailhistory',
            name='tool_exec_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_manager.ToolsExecHistory'),
        ),
    ]
